version: '3'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  quarkus-llm-client:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: quarkus-llm-client
    environment:
      - llm.base.url=http://ollama:11434
      - llm.model.name=llama3
    ports:
      - "8080:8080"
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:
